{"root": "/Users/david/Desktop/notebook_scanner/test_notebooks", "root_issues": [{"code": "UNAPPROVED_LICENSE_DEP_FILE", "severity": "MEDIUM", "details": {"package_name": "scikit-learn", "package_version": "0.19.0", "unapproved_license": "new BSD", "file_path": "/Users/david/Desktop/notebook_scanner/test_notebooks/requirements.txt"}}, {"code": "VULNERABLE_DEPENDENCY_DEP_FILE", "severity": "CRITICAL", "details": {"file_path": "/Users/david/Desktop/notebook_scanner/test_notebooks/requirements.txt", "results": {"VulnerabilityID": "CVE-2019-14234", "PkgName": "django", "InstalledVersion": "1.11.15", "FixedVersion": "1.11.23, 2.1.11, 2.2.4", "Layer": {}, "SeveritySource": "ghsa", "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2019-14234", "DataSource": {"ID": "ghsa", "Name": "GitHub Security Advisory pip", "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"}, "Title": "Django: SQL injection possibility in key and index lookups for JSONField/HStoreField", "Description": "An issue was discovered in Django 1.11.x before 1.11.23, 2.1.x before 2.1.11, and 2.2.x before 2.2.4. Due to an error in shallow key transformation, key and index lookups for django.contrib.postgres.fields.JSONField, and key lookups for django.contrib.postgres.fields.HStoreField, were subject to SQL injection. This could, for example, be exploited via crafted use of \"OR 1=1\" in a key or index name to return all records, using a suitably crafted dictionary, with dictionary expansion, as the **kwargs passed to the QuerySet.filter() function.", "Severity": "CRITICAL", "CweIDs": ["CWE-89"], "CVSS": {"ghsa": {"V3Vector": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H", "V3Score": 9.8}, "nvd": {"V2Vector": "AV:N/AC:L/Au:N/C:P/I:P/A:P", "V3Vector": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H", "V2Score": 7.5, "V3Score": 9.8}, "redhat": {"V3Vector": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N", "V3Score": 5.3}}, "References": ["http://lists.opensuse.org/opensuse-security-announce/2019-08/msg00025.html", "https://access.redhat.com/security/cve/CVE-2019-14234", "https://docs.djangoproject.com/en/dev/releases/security/", "https://github.com/django/django/commit/4f5b58f5cd3c57fee9972ab074f8dc6895d8f387", "https://github.com/django/django/commit/ed682a24fca774818542757651bfba576c3fc3ef", "https://github.com/django/django/commit/f74b3ae3628c26e1b4f8db3d13a91d52a833a975", "https://groups.google.com/forum/#!topic/django-announce/jIoju2-KLDs", "https://groups.google.com/forum/#%21topic/django-announce/jIoju2-KLDs", "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/STVX7X7IDWAH5SKE6MBMY3TEI6ZODBTK/", "https://nvd.nist.gov/vuln/detail/CVE-2019-14234", "https://seclists.org/bugtraq/2019/Aug/15", "https://security.gentoo.org/glsa/202004-17", "https://security.netapp.com/advisory/ntap-20190828-0002/", "https://ubuntu.com/security/notices/USN-4084-1", "https://www.cve.org/CVERecord?id=CVE-2019-14234", "https://www.debian.org/security/2019/dsa-4498", "https://www.djangoproject.com/weblog/2019/aug/01/security-releases", "https://www.djangoproject.com/weblog/2019/aug/01/security-releases/"], "PublishedDate": "2019-08-09T13:15:11.777Z", "LastModifiedDate": "2023-11-07T03:04:51.923Z"}}}, {"code": "VULNERABLE_DEPENDENCY_DEP_FILE", "severity": "CRITICAL", "details": {"file_path": "/Users/david/Desktop/notebook_scanner/test_notebooks/requirements.txt", "results": {"VulnerabilityID": "CVE-2019-19844", "PkgName": "django", "InstalledVersion": "1.11.15", "FixedVersion": "1.11.27, 2.2.9, 3.0.1", "Layer": {}, "SeveritySource": "ghsa", "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2019-19844", "DataSource": {"ID": "ghsa", "Name": "GitHub Security Advisory pip", "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"}, "Title": "Django: crafted email address allows account takeover", "Description": "Django before 1.11.27, 2.x before 2.2.9, and 3.x before 3.0.1 allows account takeover. A suitably crafted email address (that is equal to an existing user's email address after case transformation of Unicode characters) would allow an attacker to be sent a password reset token for the matched user account. (One mitigation in the new releases is to send password reset tokens only to the registered user email address.)", "Severity": "CRITICAL", "CweIDs": ["CWE-640"], "CVSS": {"ghsa": {"V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H", "V3Score": 9.8}, "nvd": {"V2Vector": "AV:N/AC:L/Au:N/C:N/I:P/A:N", "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H", "V2Score": 5, "V3Score": 9.8}, "redhat": {"V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H", "V3Score": 9.8}}, "References": ["http://packetstormsecurity.com/files/155872/Django-Account-Hijack.html", "https://access.redhat.com/security/cve/CVE-2019-19844", "https://docs.djangoproject.com/en/dev/releases/security/", "https://github.com/django/django", "https://github.com/django/django/commit/302a4ff1e8b1c798aab97673909c7a3dfda42c26", "https://github.com/django/django/commit/4d334bea06cac63dc1272abcec545b85136cca0e", "https://github.com/django/django/commit/5b1fbcef7a8bec991ebe7b2a18b5d5a95d72cb70", "https://github.com/django/django/commit/f4cff43bf921fcea6a29b726eb66767f67753fa2", "https://groups.google.com/forum/#!topic/django-announce/3oaB2rVH3a0", "https://groups.google.com/forum/#%21topic/django-announce/3oaB2rVH3a0", "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/HCM2DPUI7TOZWN4A6JFQFUVQ2XGE7GUD/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/HCM2DPUI7TOZWN4A6JFQFUVQ2XGE7GUD", "https://nvd.nist.gov/vuln/detail/CVE-2019-19844", "https://seclists.org/bugtraq/2020/Jan/9", "https://security.gentoo.org/glsa/202004-17", "https://security.netapp.com/advisory/ntap-20200110-0003", "https://security.netapp.com/advisory/ntap-20200110-0003/", "https://ubuntu.com/security/notices/USN-4224-1", "https://ubuntu.com/security/notices/USN-6722-1", "https://usn.ubuntu.com/4224-1", "https://usn.ubuntu.com/4224-1/", "https://www.cve.org/CVERecord?id=CVE-2019-19844", "https://www.debian.org/security/2020/dsa-4598", "https://www.djangoproject.com/weblog/2019/dec/18/security-releases", "https://www.djangoproject.com/weblog/2019/dec/18/security-releases/"], "PublishedDate": "2019-12-18T19:15:11.78Z", "LastModifiedDate": "2023-11-07T03:07:49.577Z"}}}, {"code": "VULNERABLE_DEPENDENCY_DEP_FILE", "severity": "CRITICAL", "details": {"file_path": "/Users/david/Desktop/notebook_scanner/test_notebooks/requirements.txt", "results": {"VulnerabilityID": "CVE-2020-7471", "PkgName": "django", "InstalledVersion": "1.11.15", "FixedVersion": "1.11.28, 2.2.10, 3.0.3", "Layer": {}, "SeveritySource": "ghsa", "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2020-7471", "DataSource": {"ID": "ghsa", "Name": "GitHub Security Advisory pip", "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"}, "Title": "django: potential SQL injection via StringAgg(delimiter)", "Description": "Django 1.11 before 1.11.28, 2.2 before 2.2.10, and 3.0 before 3.0.3 allows SQL Injection if untrusted data is used as a StringAgg delimiter (e.g., in Django applications that offer downloads of data as a series of rows with a user-specified column delimiter). By passing a suitably crafted delimiter to a contrib.postgres.aggregates.StringAgg instance, it was possible to break escaping and inject malicious SQL.", "Severity": "CRITICAL", "CweIDs": ["CWE-89"], "CVSS": {"bitnami": {"V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H", "V3Score": 9.8}, "ghsa": {"V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H", "V3Score": 9.8}, "nvd": {"V2Vector": "AV:N/AC:L/Au:N/C:P/I:P/A:P", "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H", "V2Score": 7.5, "V3Score": 9.8}, "redhat": {"V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H", "V3Score": 9.8}}, "References": ["http://www.openwall.com/lists/oss-security/2020/02/03/1", "https://access.redhat.com/security/cve/CVE-2020-7471", "https://docs.djangoproject.com/en/3.0/releases/security/", "https://github.com/django/django", "https://github.com/django/django/commit/001b0634cd309e372edb6d7d95d083d02b8e37bd", "https://github.com/django/django/commit/505826b469b16ab36693360da9e11fd13213421b", "https://github.com/django/django/commit/c67a368c16e4680b324b4f385398d638db4d8147", "https://github.com/django/django/commit/eb31d845323618d688ad429479c6dda973056136", "https://groups.google.com/forum/#!topic/django-announce/X45S86X5bZI", "https://groups.google.com/forum/#%21topic/django-announce/X45S86X5bZI", "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/4A2AP4T7RKPBCLTI2NNQG3T6MINDUUMZ/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/4A2AP4T7RKPBCLTI2NNQG3T6MINDUUMZ", "https://nvd.nist.gov/vuln/detail/CVE-2020-7471", "https://seclists.org/bugtraq/2020/Feb/30", "https://security.gentoo.org/glsa/202004-17", "https://security.netapp.com/advisory/ntap-20200221-0006", "https://security.netapp.com/advisory/ntap-20200221-0006/", "https://ubuntu.com/security/notices/USN-4264-1", "https://usn.ubuntu.com/4264-1", "https://usn.ubuntu.com/4264-1/", "https://www.cve.org/CVERecord?id=CVE-2020-7471", "https://www.debian.org/security/2020/dsa-4629", "https://www.djangoproject.com/weblog/2020/feb/03/security-releases", "https://www.djangoproject.com/weblog/2020/feb/03/security-releases/", "https://www.openwall.com/lists/oss-security/2020/02/03/1"], "PublishedDate": "2020-02-03T12:15:26.993Z", "LastModifiedDate": "2023-11-07T03:26:06.483Z"}}}, {"code": "VULNERABLE_DEPENDENCY_DEP_FILE", "severity": "HIGH", "details": {"file_path": "/Users/david/Desktop/notebook_scanner/test_notebooks/requirements.txt", "results": {"VulnerabilityID": "CVE-2019-14232", "PkgName": "django", "InstalledVersion": "1.11.15", "FixedVersion": "1.11.23, 2.1.11, 2.2.4", "Layer": {}, "SeveritySource": "ghsa", "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2019-14232", "DataSource": {"ID": "ghsa", "Name": "GitHub Security Advisory pip", "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"}, "Title": "Django: backtracking in a regular expression in django.utils.text.Truncator leads to DoS", "Description": "An issue was discovered in Django 1.11.x before 1.11.23, 2.1.x before 2.1.11, and 2.2.x before 2.2.4. If django.utils.text.Truncator's chars() and words() methods were passed the html=True argument, they were extremely slow to evaluate certain inputs due to a catastrophic backtracking vulnerability in a regular expression. The chars() and words() methods are used to implement the truncatechars_html and truncatewords_html template filters, which were thus vulnerable.", "Severity": "HIGH", "CweIDs": ["CWE-400"], "CVSS": {"ghsa": {"V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H", "V3Score": 7.5}, "nvd": {"V2Vector": "AV:N/AC:L/Au:N/C:N/I:N/A:P", "V3Vector": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H", "V2Score": 5, "V3Score": 7.5}, "redhat": {"V3Vector": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:L", "V3Score": 5.3}}, "References": ["http://lists.opensuse.org/opensuse-security-announce/2019-08/msg00006.html", "http://lists.opensuse.org/opensuse-security-announce/2019-08/msg00025.html", "http://www.openwall.com/lists/oss-security/2023/10/04/6", "http://www.openwall.com/lists/oss-security/2024/03/04/1", "https://access.redhat.com/security/cve/CVE-2019-14232", "https://docs.djangoproject.com/en/dev/releases/security", "https://docs.djangoproject.com/en/dev/releases/security/", "https://github.com/django/django", "https://github.com/pypa/advisory-db/tree/main/vulns/django/PYSEC-2019-11.yaml", "https://groups.google.com/forum/#!topic/django-announce/jIoju2-KLDs", "https://groups.google.com/forum/#%21topic/django-announce/jIoju2-KLDs", "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/STVX7X7IDWAH5SKE6MBMY3TEI6ZODBTK", "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/STVX7X7IDWAH5SKE6MBMY3TEI6ZODBTK/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/STVX7X7IDWAH5SKE6MBMY3TEI6ZODBTK", "https://lists.opensuse.org/archives/list/security-announce@lists.opensuse.org/message/3LGJSPCN3VEG2UJPYCUB6TU75JTIV2TQ", "https://lists.opensuse.org/archives/list/security-announce@lists.opensuse.org/message/5XTP44JEOSNXRVW4JDZXA5XGMBDZLWSW", "https://nvd.nist.gov/vuln/detail/CVE-2019-14232", "https://seclists.org/bugtraq/2019/Aug/15", "https://security.gentoo.org/glsa/202004-17", "https://security.netapp.com/advisory/ntap-20190828-0002", "https://security.netapp.com/advisory/ntap-20190828-0002/", "https://ubuntu.com/security/notices/USN-4084-1", "https://www.cve.org/CVERecord?id=CVE-2019-14232", "https://www.debian.org/security/2019/dsa-4498", "https://www.djangoproject.com/weblog/2019/aug/01/security-releases", "https://www.djangoproject.com/weblog/2019/aug/01/security-releases/", "https://www.openwall.com/lists/oss-security/2023/10/04/6"], "PublishedDate": "2019-08-02T15:15:11.88Z", "LastModifiedDate": "2024-07-03T01:35:42.547Z"}}}, {"code": "VULNERABLE_DEPENDENCY_DEP_FILE", "severity": "HIGH", "details": {"file_path": "/Users/david/Desktop/notebook_scanner/test_notebooks/requirements.txt", "results": {"VulnerabilityID": "CVE-2019-14233", "PkgName": "django", "InstalledVersion": "1.11.15", "FixedVersion": "1.11.23, 2.1.11, 2.2.4", "Layer": {}, "SeveritySource": "ghsa", "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2019-14233", "DataSource": {"ID": "ghsa", "Name": "GitHub Security Advisory pip", "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"}, "Title": "Django: the behavior of the underlying HTMLParser leading to DoS", "Description": "An issue was discovered in Django 1.11.x before 1.11.23, 2.1.x before 2.1.11, and 2.2.x before 2.2.4. Due to the behaviour of the underlying HTMLParser, django.utils.html.strip_tags would be extremely slow to evaluate certain inputs containing large sequences of nested incomplete HTML entities.", "Severity": "HIGH", "CweIDs": ["CWE-400"], "CVSS": {"ghsa": {"V3Vector": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H", "V3Score": 7.5}, "nvd": {"V2Vector": "AV:N/AC:L/Au:N/C:N/I:N/A:P", "V3Vector": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H", "V2Score": 5, "V3Score": 7.5}, "redhat": {"V3Vector": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:L", "V3Score": 5.3}}, "References": ["http://lists.opensuse.org/opensuse-security-announce/2019-08/msg00006.html", "http://lists.opensuse.org/opensuse-security-announce/2019-08/msg00025.html", "https://access.redhat.com/security/cve/CVE-2019-14233", "https://docs.djangoproject.com/en/dev/releases/security", "https://docs.djangoproject.com/en/dev/releases/security/", "https://github.com/django/django", "https://groups.google.com/forum/#!topic/django-announce/jIoju2-KLDs", "https://groups.google.com/forum/#%21topic/django-announce/jIoju2-KLDs", "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/STVX7X7IDWAH5SKE6MBMY3TEI6ZODBTK/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/STVX7X7IDWAH5SKE6MBMY3TEI6ZODBTK", "https://nvd.nist.gov/vuln/detail/CVE-2019-14233", "https://seclists.org/bugtraq/2019/Aug/15", "https://security.gentoo.org/glsa/202004-17", "https://security.netapp.com/advisory/ntap-20190828-0002", "https://security.netapp.com/advisory/ntap-20190828-0002/", "https://ubuntu.com/security/notices/USN-4084-1", "https://www.cve.org/CVERecord?id=CVE-2019-14233", "https://www.debian.org/security/2019/dsa-4498", "https://www.djangoproject.com/weblog/2019/aug/01/security-releases", "https://www.djangoproject.com/weblog/2019/aug/01/security-releases/"], "PublishedDate": "2019-08-02T15:15:11.943Z", "LastModifiedDate": "2023-11-07T03:04:51.85Z"}}}, {"code": "VULNERABLE_DEPENDENCY_DEP_FILE", "severity": "HIGH", "details": {"file_path": "/Users/david/Desktop/notebook_scanner/test_notebooks/requirements.txt", "results": {"VulnerabilityID": "CVE-2019-14235", "PkgName": "django", "InstalledVersion": "1.11.15", "FixedVersion": "1.11.23, 2.1.11, 2.2.4", "Layer": {}, "SeveritySource": "ghsa", "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2019-14235", "DataSource": {"ID": "ghsa", "Name": "GitHub Security Advisory pip", "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"}, "Title": "Django: Potential memory exhaustion in django.utils.encoding.uri_to_iri()", "Description": "An issue was discovered in Django 1.11.x before 1.11.23, 2.1.x before 2.1.11, and 2.2.x before 2.2.4. If passed certain inputs, django.utils.encoding.uri_to_iri could lead to significant memory usage due to a recursion when repercent-encoding invalid UTF-8 octet sequences.", "Severity": "HIGH", "CweIDs": ["CWE-674"], "CVSS": {"ghsa": {"V3Vector": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H", "V3Score": 7.5}, "nvd": {"V2Vector": "AV:N/AC:L/Au:N/C:N/I:N/A:P", "V3Vector": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H", "V2Score": 5, "V3Score": 7.5}, "redhat": {"V3Vector": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:L", "V3Score": 5.3}}, "References": ["http://lists.opensuse.org/opensuse-security-announce/2019-08/msg00006.html", "http://lists.opensuse.org/opensuse-security-announce/2019-08/msg00025.html", "https://access.redhat.com/security/cve/CVE-2019-14235", "https://docs.djangoproject.com/en/dev/releases/security", "https://docs.djangoproject.com/en/dev/releases/security/", "https://groups.google.com/forum/#!topic/django-announce/jIoju2-KLDs", "https://groups.google.com/forum/#%21topic/django-announce/jIoju2-KLDs", "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/STVX7X7IDWAH5SKE6MBMY3TEI6ZODBTK/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/STVX7X7IDWAH5SKE6MBMY3TEI6ZODBTK", "https://nvd.nist.gov/vuln/detail/CVE-2019-14235", "https://seclists.org/bugtraq/2019/Aug/15", "https://security.gentoo.org/glsa/202004-17", "https://security.netapp.com/advisory/ntap-20190828-0002", "https://security.netapp.com/advisory/ntap-20190828-0002/", "https://ubuntu.com/security/notices/USN-4084-1", "https://www.cve.org/CVERecord?id=CVE-2019-14235", "https://www.debian.org/security/2019/dsa-4498", "https://www.djangoproject.com/weblog/2019/aug/01/security-releases", "https://www.djangoproject.com/weblog/2019/aug/01/security-releases/"], "PublishedDate": "2019-08-02T15:15:12.023Z", "LastModifiedDate": "2023-11-07T03:04:52.01Z"}}}, {"code": "VULNERABLE_DEPENDENCY_DEP_FILE", "severity": "HIGH", "details": {"file_path": "/Users/david/Desktop/notebook_scanner/test_notebooks/requirements.txt", "results": {"VulnerabilityID": "CVE-2019-6975", "PkgName": "django", "InstalledVersion": "1.11.15", "FixedVersion": "1.11.19, 2.0.11, 2.1.6", "Layer": {}, "SeveritySource": "ghsa", "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2019-6975", "DataSource": {"ID": "ghsa", "Name": "GitHub Security Advisory pip", "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"}, "Title": "python-django: memory exhaustion in django.utils.numberformat.format()", "Description": "Django 1.11.x before 1.11.19, 2.0.x before 2.0.11, and 2.1.x before 2.1.6 allows Uncontrolled Memory Consumption via a malicious attacker-supplied value to the django.utils.numberformat.format() function.", "Severity": "HIGH", "CweIDs": ["CWE-770"], "CVSS": {"ghsa": {"V3Vector": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H", "V3Score": 7.5}, "nvd": {"V2Vector": "AV:N/AC:L/Au:N/C:N/I:N/A:P", "V3Vector": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H", "V2Score": 5, "V3Score": 7.5}, "redhat": {"V3Vector": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:L", "V3Score": 5.3}}, "References": ["http://www.securityfocus.com/bid/106964", "https://access.redhat.com/security/cve/CVE-2019-6975", "https://docs.djangoproject.com/en/dev/releases/security", "https://docs.djangoproject.com/en/dev/releases/security/", "https://github.com/django/django", "https://github.com/django/django/commit/0bbb560183fabf0533289700845dafa94951f227", "https://github.com/django/django/commit/1f42f82566c9d2d73aff1c42790d6b1b243f7676", "https://github.com/django/django/commit/40cd19055773705301c3428ed5e08a036d2091f3", "https://groups.google.com/forum/#!topic/django-announce/WTwEAprR0IQ", "https://groups.google.com/forum/#%21topic/django-announce/WTwEAprR0IQ", "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/66WMXHGBXD7GSM3PEXVCMCAGLMQYHZCU/", "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/HVXDOVCXLD74SHR2BENGCE2OOYYYWJHZ/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/66WMXHGBXD7GSM3PEXVCMCAGLMQYHZCU", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/HVXDOVCXLD74SHR2BENGCE2OOYYYWJHZ", "https://nvd.nist.gov/vuln/detail/CVE-2019-6975", "https://seclists.org/bugtraq/2019/Jul/10", "https://ubuntu.com/security/notices/USN-3890-1", "https://usn.ubuntu.com/3890-1", "https://usn.ubuntu.com/3890-1/", "https://web.archive.org/web/20200227084713/http://www.securityfocus.com/bid/106964", "https://www.cve.org/CVERecord?id=CVE-2019-6975", "https://www.debian.org/security/2019/dsa-4476", "https://www.djangoproject.com/weblog/2019/feb/11/security-releases", "https://www.djangoproject.com/weblog/2019/feb/11/security-releases/", "https://www.openwall.com/lists/oss-security/2019/02/11/1"], "PublishedDate": "2019-02-11T13:29:00.27Z", "LastModifiedDate": "2023-11-07T03:13:16.437Z"}}}, {"code": "VULNERABLE_DEPENDENCY_DEP_FILE", "severity": "HIGH", "details": {"file_path": "/Users/david/Desktop/notebook_scanner/test_notebooks/requirements.txt", "results": {"VulnerabilityID": "CVE-2020-9402", "PkgName": "django", "InstalledVersion": "1.11.15", "FixedVersion": "1.11.29, 2.2.11, 3.0.4", "Layer": {}, "SeveritySource": "ghsa", "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2020-9402", "DataSource": {"ID": "ghsa", "Name": "GitHub Security Advisory pip", "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"}, "Title": "django: potential SQL injection via \"tolerance\" parameter in GIS functions and aggregates on Oracle", "Description": "Django 1.11 before 1.11.29, 2.2 before 2.2.11, and 3.0 before 3.0.4 allows SQL Injection if untrusted data is used as a tolerance parameter in GIS functions and aggregates on Oracle. By passing a suitably crafted tolerance to GIS functions and aggregates on Oracle, it was possible to break escaping and inject malicious SQL.", "Severity": "HIGH", "CweIDs": ["CWE-89"], "CVSS": {"bitnami": {"V3Vector": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H", "V3Score": 8.8}, "ghsa": {"V3Vector": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H", "V3Score": 8.8}, "nvd": {"V2Vector": "AV:N/AC:L/Au:S/C:P/I:P/A:P", "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H", "V2Score": 6.5, "V3Score": 8.8}, "redhat": {"V3Vector": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H", "V3Score": 8.8}}, "References": ["https://access.redhat.com/security/cve/CVE-2020-9402", "https://docs.djangoproject.com/en/3.0/releases/security", "https://docs.djangoproject.com/en/3.0/releases/security/", "https://github.com/django/django", "https://github.com/django/django/commit/6695d29b1c1ce979725816295a26ecc64ae0e927", "https://groups.google.com/forum/#!topic/django-announce/fLUh_pOaKrY", "https://groups.google.com/forum/#%21topic/django-announce/fLUh_pOaKrY", "https://lists.debian.org/debian-lts-announce/2022/05/msg00035.html", "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/4A2AP4T7RKPBCLTI2NNQG3T6MINDUUMZ/", "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/UZMN2NKAGTFE3YKMNM2JVJG7R2W7LLHY/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/4A2AP4T7RKPBCLTI2NNQG3T6MINDUUMZ", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/UZMN2NKAGTFE3YKMNM2JVJG7R2W7LLHY", "https://nvd.nist.gov/vuln/detail/CVE-2020-9402", "https://security.gentoo.org/glsa/202004-17", "https://security.netapp.com/advisory/ntap-20200327-0004", "https://security.netapp.com/advisory/ntap-20200327-0004/", "https://ubuntu.com/security/notices/USN-4296-1", "https://usn.ubuntu.com/4296-1", "https://usn.ubuntu.com/4296-1/", "https://www.cve.org/CVERecord?id=CVE-2020-9402", "https://www.debian.org/security/2020/dsa-4705", "https://www.djangoproject.com/weblog/2020/mar/04/security-releases", "https://www.djangoproject.com/weblog/2020/mar/04/security-releases/"], "PublishedDate": "2020-03-05T15:15:12.41Z", "LastModifiedDate": "2023-11-07T03:26:52.05Z"}}}, {"code": "VULNERABLE_DEPENDENCY_DEP_FILE", "severity": "HIGH", "details": {"file_path": "/Users/david/Desktop/notebook_scanner/test_notebooks/requirements.txt", "results": {"VulnerabilityID": "CVE-2021-44420", "PkgName": "django", "InstalledVersion": "1.11.15", "FixedVersion": "2.2.25, 3.1.14, 3.2.10", "Layer": {}, "SeveritySource": "ghsa", "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2021-44420", "DataSource": {"ID": "ghsa", "Name": "GitHub Security Advisory pip", "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"}, "Title": "django: potential bypass of an upstream access control based on URL paths", "Description": "In Django 2.2 before 2.2.25, 3.1 before 3.1.14, and 3.2 before 3.2.10, HTTP requests for URLs with trailing newlines could bypass upstream access control based on URL paths.", "Severity": "HIGH", "CVSS": {"bitnami": {"V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:L/A:L", "V3Score": 7.3}, "ghsa": {"V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:L/A:L", "V3Score": 7.3}, "nvd": {"V2Vector": "AV:N/AC:L/Au:N/C:P/I:P/A:P", "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:L/A:L", "V2Score": 7.5, "V3Score": 7.3}, "redhat": {"V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N", "V3Score": 5.3}}, "References": ["https://access.redhat.com/security/cve/CVE-2021-44420", "https://docs.djangoproject.com/en/3.2/releases/security", "https://docs.djangoproject.com/en/3.2/releases/security/", "https://github.com/django/django", "https://github.com/django/django/commit/d4dcd5b9dd9e462fec8220e33e3e6c822b7e88a6", "https://groups.google.com/forum/#!forum/django-announce", "https://groups.google.com/forum/#%21forum/django-announce", "https://linux.oracle.com/cve/CVE-2021-44420.html", "https://linux.oracle.com/errata/ELSA-2022-9341.html", "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/B4SQG2EAF4WCI2SLRL6XRDJ3RPK3ZRDV/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/B4SQG2EAF4WCI2SLRL6XRDJ3RPK3ZRDV", "https://nvd.nist.gov/vuln/detail/CVE-2021-44420", "https://security.netapp.com/advisory/ntap-20211229-0006", "https://security.netapp.com/advisory/ntap-20211229-0006/", "https://ubuntu.com/security/notices/USN-5178-1", "https://www.cve.org/CVERecord?id=CVE-2021-44420", "https://www.djangoproject.com/weblog/2021/dec/07/security-releases", "https://www.djangoproject.com/weblog/2021/dec/07/security-releases/", "https://www.openwall.com/lists/oss-security/2021/12/07/1"], "PublishedDate": "2021-12-08T00:15:07.757Z", "LastModifiedDate": "2023-11-07T03:39:38.7Z"}}}, {"code": "VULNERABLE_DEPENDENCY_DEP_FILE", "severity": "MEDIUM", "details": {"file_path": "/Users/david/Desktop/notebook_scanner/test_notebooks/requirements.txt", "results": {"VulnerabilityID": "CVE-2019-12308", "PkgName": "django", "InstalledVersion": "1.11.15", "FixedVersion": "1.11.21, 2.1.9, 2.2.2", "Layer": {}, "SeveritySource": "ghsa", "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2019-12308", "DataSource": {"ID": "ghsa", "Name": "GitHub Security Advisory pip", "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"}, "Title": "django: missing URL validation by AdminURLFieldWidget leads to generation of clickable unsafe JavaScript link causing cross site scripting", "Description": "An issue was discovered in Django 1.11 before 1.11.21, 2.1 before 2.1.9, and 2.2 before 2.2.2. The clickable Current URL value displayed by the AdminURLFieldWidget displays the provided value without validating it as a safe URL. Thus, an unvalidated value stored in the database, or a value provided as a URL query parameter payload, could result in an clickable JavaScript link.", "Severity": "MEDIUM", "CweIDs": ["CWE-79"], "CVSS": {"ghsa": {"V3Vector": "CVSS:3.0/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N", "V3Score": 6.1}, "nvd": {"V2Vector": "AV:N/AC:M/Au:N/C:N/I:P/A:N", "V3Vector": "CVSS:3.0/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N", "V2Score": 4.3, "V3Score": 6.1}, "redhat": {"V3Vector": "CVSS:3.0/AV:N/AC:L/PR:N/UI:R/S:C/C:N/I:L/A:N", "V3Score": 4.7}}, "References": ["http://lists.opensuse.org/opensuse-security-announce/2019-08/msg00006.html", "http://lists.opensuse.org/opensuse-security-announce/2019-08/msg00025.html", "http://www.openwall.com/lists/oss-security/2019/06/03/2", "http://www.securityfocus.com/bid/108559", "https://access.redhat.com/security/cve/CVE-2019-12308", "https://docs.djangoproject.com/en/2.1/releases/2.1.9/", "https://docs.djangoproject.com/en/2.2/releases/1.11.21/", "https://docs.djangoproject.com/en/2.2/releases/2.2.2/", "https://docs.djangoproject.com/en/dev/releases/1.11.21", "https://docs.djangoproject.com/en/dev/releases/1.11.21/", "https://docs.djangoproject.com/en/dev/releases/2.1.9", "https://docs.djangoproject.com/en/dev/releases/2.1.9/", "https://docs.djangoproject.com/en/dev/releases/2.2.2", "https://docs.djangoproject.com/en/dev/releases/2.2.2/", "https://docs.djangoproject.com/en/dev/releases/security", "https://docs.djangoproject.com/en/dev/releases/security/", "https://github.com/django/django", "https://github.com/django/django/commit/09186a13d975de6d049f8b3e05484f66b01ece62", "https://github.com/django/django/commit/afddabf8428ddc89a332f7a78d0d21eaf2b5a673", "https://github.com/django/django/commit/c238701859a52d584f349cce15d56c8e8137c52b", "https://groups.google.com/forum/#!topic/django-announce/GEbHU7YoVz8", "https://groups.google.com/forum/#%21topic/django-announce/GEbHU7YoVz8", "https://lists.debian.org/debian-lts-announce/2019/06/msg00001.html", "https://lists.debian.org/debian-lts-announce/2019/07/msg00001.html", "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/USYRARSYB7PE3S2ZQO7PZNWMH7RPGL5G/", "https://nvd.nist.gov/vuln/detail/CVE-2019-12308", "https://seclists.org/bugtraq/2019/Jul/10", "https://security.gentoo.org/glsa/202004-17", "https://ubuntu.com/security/notices/USN-4043-1", "https://usn.ubuntu.com/4043-1/", "https://www.cve.org/CVERecord?id=CVE-2019-12308", "https://www.debian.org/security/2019/dsa-4476", "https://www.djangoproject.com/weblog/2019/jun/03/security-releases", "https://www.djangoproject.com/weblog/2019/jun/03/security-releases/"], "PublishedDate": "2019-06-03T17:29:01.213Z", "LastModifiedDate": "2023-11-07T03:03:31.32Z"}}}, {"code": "VULNERABLE_DEPENDENCY_DEP_FILE", "severity": "MEDIUM", "details": {"file_path": "/Users/david/Desktop/notebook_scanner/test_notebooks/requirements.txt", "results": {"VulnerabilityID": "CVE-2019-12781", "PkgName": "django", "InstalledVersion": "1.11.15", "FixedVersion": "1.11.22, 2.1.10, 2.2.3", "Layer": {}, "SeveritySource": "ghsa", "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2019-12781", "DataSource": {"ID": "ghsa", "Name": "GitHub Security Advisory pip", "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"}, "Title": "Django: Incorrect HTTP detection with reverse-proxy connecting via HTTPS", "Description": "An issue was discovered in Django 1.11 before 1.11.22, 2.1 before 2.1.10, and 2.2 before 2.2.3. An HTTP request is not redirected to HTTPS when the SECURE_PROXY_SSL_HEADER and SECURE_SSL_REDIRECT settings are used, and the proxy connects to Django via HTTPS. In other words, django.http.HttpRequest.scheme has incorrect behavior when a client uses HTTP.", "Severity": "MEDIUM", "CweIDs": ["CWE-319"], "CVSS": {"ghsa": {"V3Vector": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N", "V3Score": 5.3}, "nvd": {"V2Vector": "AV:N/AC:L/Au:N/C:P/I:N/A:N", "V3Vector": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N", "V2Score": 5, "V3Score": 5.3}, "redhat": {"V3Vector": "CVSS:3.0/AV:N/AC:H/PR:N/UI:N/S:U/C:L/I:L/A:N", "V3Score": 4.8}}, "References": ["http://lists.opensuse.org/opensuse-security-announce/2019-08/msg00006.html", "http://lists.opensuse.org/opensuse-security-announce/2019-08/msg00025.html", "http://www.openwall.com/lists/oss-security/2019/07/01/3", "http://www.securityfocus.com/bid/109018", "https://access.redhat.com/security/cve/CVE-2019-12781", "https://docs.djangoproject.com/en/dev/releases/security", "https://docs.djangoproject.com/en/dev/releases/security/", "https://github.com/django/django", "https://groups.google.com/forum/#!topic/django-announce/Is4kLY9ZcZQ", "https://groups.google.com/forum/#%21topic/django-announce/Is4kLY9ZcZQ", "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/5VXXWIOQGXOB7JCGJ3CVUW673LDHKEYL/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/5VXXWIOQGXOB7JCGJ3CVUW673LDHKEYL", "https://nvd.nist.gov/vuln/detail/CVE-2019-12781", "https://seclists.org/bugtraq/2019/Jul/10", "https://security.netapp.com/advisory/ntap-20190705-0002", "https://security.netapp.com/advisory/ntap-20190705-0002/", "https://ubuntu.com/security/notices/USN-4043-1", "https://usn.ubuntu.com/4043-1", "https://usn.ubuntu.com/4043-1/", "https://www.cve.org/CVERecord?id=CVE-2019-12781", "https://www.debian.org/security/2019/dsa-4476", "https://www.djangoproject.com/weblog/2019/jul/01/security-releases", "https://www.djangoproject.com/weblog/2019/jul/01/security-releases/"], "PublishedDate": "2019-07-01T14:15:10.847Z", "LastModifiedDate": "2023-11-07T03:03:40.713Z"}}}, {"code": "VULNERABLE_DEPENDENCY_DEP_FILE", "severity": "MEDIUM", "details": {"file_path": "/Users/david/Desktop/notebook_scanner/test_notebooks/requirements.txt", "results": {"VulnerabilityID": "CVE-2019-3498", "PkgName": "django", "InstalledVersion": "1.11.15", "FixedVersion": "1.11.18, 2.0.10, 2.1.5", "Layer": {}, "SeveritySource": "ghsa", "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2019-3498", "DataSource": {"ID": "ghsa", "Name": "GitHub Security Advisory pip", "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"}, "Title": "python-django: Content spoofing via URL path in default 404 page", "Description": "In Django 1.11.x before 1.11.18, 2.0.x before 2.0.10, and 2.1.x before 2.1.5, an Improper Neutralization of Special Elements in Output Used by a Downstream Component issue exists in django.views.defaults.page_not_found(), leading to content spoofing (in a 404 error page) if a user fails to recognize that a crafted URL has malicious content.", "Severity": "MEDIUM", "CweIDs": ["CWE-74"], "CVSS": {"ghsa": {"V3Vector": "CVSS:3.0/AV:N/AC:L/PR:N/UI:R/S:U/C:N/I:H/A:N", "V3Score": 6.5}, "nvd": {"V2Vector": "AV:N/AC:M/Au:N/C:N/I:P/A:N", "V3Vector": "CVSS:3.0/AV:N/AC:L/PR:N/UI:R/S:U/C:N/I:H/A:N", "V2Score": 4.3, "V3Score": 6.5}, "redhat": {"V3Vector": "CVSS:3.0/AV:N/AC:L/PR:N/UI:R/S:U/C:N/I:L/A:N", "V3Score": 4.3}}, "References": ["http://www.securityfocus.com/bid/106453", "https://access.redhat.com/security/cve/CVE-2019-3498", "https://docs.djangoproject.com/en/dev/releases/security", "https://docs.djangoproject.com/en/dev/releases/security/", "https://github.com/advisories/GHSA-337x-4q8g-prc5", "https://groups.google.com/forum/#!topic/django-announce/VYU7xQQTEPQ", "https://groups.google.com/forum/#%21topic/django-announce/VYU7xQQTEPQ", "https://lists.debian.org/debian-lts-announce/2019/01/msg00005.html", "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/HVXDOVCXLD74SHR2BENGCE2OOYYYWJHZ/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/HVXDOVCXLD74SHR2BENGCE2OOYYYWJHZ", "https://nvd.nist.gov/vuln/detail/CVE-2019-3498", "https://ubuntu.com/security/notices/USN-3851-1", "https://usn.ubuntu.com/3851-1", "https://usn.ubuntu.com/3851-1/", "https://web.archive.org/web/20200227094237/http://www.securityfocus.com/bid/106453", "https://www.cve.org/CVERecord?id=CVE-2019-3498", "https://www.debian.org/security/2019/dsa-4363", "https://www.djangoproject.com/weblog/2019/jan/04/security-releases", "https://www.djangoproject.com/weblog/2019/jan/04/security-releases/"], "PublishedDate": "2019-01-09T23:29:05.387Z", "LastModifiedDate": "2023-11-07T03:09:53.503Z"}}}, {"code": "VULNERABLE_DEPENDENCY_DEP_FILE", "severity": "MEDIUM", "details": {"file_path": "/Users/david/Desktop/notebook_scanner/test_notebooks/requirements.txt", "results": {"VulnerabilityID": "CVE-2021-33203", "PkgName": "django", "InstalledVersion": "1.11.15", "FixedVersion": "2.2.24, 3.1.12, 3.2.4", "Layer": {}, "SeveritySource": "ghsa", "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2021-33203", "DataSource": {"ID": "ghsa", "Name": "GitHub Security Advisory pip", "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"}, "Title": "django: Potential directory traversal via ``admindocs``", "Description": "Django before 2.2.24, 3.x before 3.1.12, and 3.2.x before 3.2.4 has a potential directory traversal via django.contrib.admindocs. Staff members could use the TemplateDetailView view to check the existence of arbitrary files. Additionally, if (and only if) the default admindocs templates have been customized by application developers to also show file contents, then not only the existence but also the file contents would have been exposed. In other words, there is directory traversal outside of the template root directories.", "Severity": "MEDIUM", "CweIDs": ["CWE-22"], "CVSS": {"bitnami": {"V3Vector": "CVSS:3.1/AV:N/AC:L/PR:H/UI:N/S:U/C:H/I:N/A:N", "V3Score": 4.9}, "ghsa": {"V3Vector": "CVSS:3.1/AV:N/AC:L/PR:H/UI:N/S:U/C:H/I:N/A:N", "V3Score": 4.9}, "nvd": {"V2Vector": "AV:N/AC:L/Au:S/C:P/I:N/A:N", "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:H/UI:N/S:U/C:H/I:N/A:N", "V2Score": 4, "V3Score": 4.9}, "redhat": {"V3Vector": "CVSS:3.1/AV:N/AC:L/PR:H/UI:N/S:U/C:H/I:N/A:N", "V3Score": 4.9}}, "References": ["https://access.redhat.com/security/cve/CVE-2021-33203", "https://docs.djangoproject.com/en/3.2/releases/security", "https://docs.djangoproject.com/en/3.2/releases/security/", "https://github.com/django/django", "https://github.com/django/django/commit/053cc9534d174dc89daba36724ed2dcb36755b90", "https://github.com/django/django/commit/20c67a0693c4ede2b09af02574823485e82e4c8f", "https://github.com/django/django/commit/dfaba12cda060b8b292ae1d271b44bf810b1c5b9", "https://groups.google.com/forum/#!forum/django-announce", "https://groups.google.com/forum/#%21forum/django-announce", "https://linux.oracle.com/cve/CVE-2021-33203.html", "https://linux.oracle.com/errata/ELSA-2022-9341.html", "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/B4SQG2EAF4WCI2SLRL6XRDJ3RPK3ZRDV/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/B4SQG2EAF4WCI2SLRL6XRDJ3RPK3ZRDV", "https://nvd.nist.gov/vuln/detail/CVE-2021-33203", "https://security.netapp.com/advisory/ntap-20210727-0004", "https://security.netapp.com/advisory/ntap-20210727-0004/", "https://ubuntu.com/security/notices/USN-4975-1", "https://ubuntu.com/security/notices/USN-4975-2", "https://www.cve.org/CVERecord?id=CVE-2021-33203", "https://www.djangoproject.com/weblog/2021/jun/02/security-releases", "https://www.djangoproject.com/weblog/2021/jun/02/security-releases/"], "PublishedDate": "2021-06-08T18:15:08.48Z", "LastModifiedDate": "2023-11-07T03:35:49.333Z"}}}, {"code": "VULNERABLE_DEPENDENCY_DEP_FILE", "severity": "MEDIUM", "details": {"file_path": "/Users/david/Desktop/notebook_scanner/test_notebooks/requirements.txt", "results": {"VulnerabilityID": "CVE-2024-24680", "PkgName": "django", "InstalledVersion": "1.11.15", "FixedVersion": "3.2.24, 4.2.10, 5.0.2", "Layer": {}, "SeveritySource": "ghsa", "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2024-24680", "DataSource": {"ID": "ghsa", "Name": "GitHub Security Advisory pip", "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"}, "Title": "Django: denial-of-service in ``intcomma`` template filter", "Description": "An issue was discovered in Django 3.2 before 3.2.24, 4.2 before 4.2.10, and Django 5.0 before 5.0.2. The intcomma template filter was subject to a potential denial-of-service attack when used with very long strings.", "Severity": "MEDIUM", "CVSS": {"bitnami": {"V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H", "V3Score": 7.5}, "ghsa": {"V3Vector": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:N/I:N/A:H", "V3Score": 5.9}, "nvd": {"V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H", "V3Score": 7.5}, "redhat": {"V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H", "V3Score": 7.5}}, "References": ["https://access.redhat.com/security/cve/CVE-2024-24680", "https://docs.djangoproject.com/en/5.0/releases/security", "https://docs.djangoproject.com/en/5.0/releases/security/", "https://github.com/advisories/GHSA-xxj9-f6rv-m3x4", "https://github.com/django/django", "https://github.com/django/django/commit/16a8fe18a3b81250f4fa57e3f93f0599dc4895bc", "https://github.com/django/django/commit/55519d6cf8998fe4c8f5c8abffc2b10a7c3d14e9", "https://github.com/django/django/commit/572ea07e84b38ea8de0551f4b4eda685d91d09d2", "https://github.com/django/django/commit/c1171ffbd570db90ca206c30f8e2b9f691243820", "https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2024-28.yaml", "https://groups.google.com/forum/#%21forum/django-announce", "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/D2JIRXEDP4ZET5KFMAPPYSK663Q52NEX", "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/D2JIRXEDP4ZET5KFMAPPYSK663Q52NEX/", "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/SN2PLJGYSAAG5KUVIUFJYKD3BLQ4OSN6", "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/SN2PLJGYSAAG5KUVIUFJYKD3BLQ4OSN6/", "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/ZQJOMNRMVPCN5WMIZ7YSX5LQ7IR2NY4D", "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/ZQJOMNRMVPCN5WMIZ7YSX5LQ7IR2NY4D/", "https://nvd.nist.gov/vuln/detail/CVE-2024-24680", "https://ubuntu.com/security/notices/USN-6623-1", "https://www.cve.org/CVERecord?id=CVE-2024-24680", "https://www.djangoproject.com/weblog/2024/feb/06/security-releases", "https://www.djangoproject.com/weblog/2024/feb/06/security-releases/"], "PublishedDate": "2024-02-06T22:16:15.47Z", "LastModifiedDate": "2024-04-20T03:15:06.82Z"}}}, {"code": "VULNERABLE_DEPENDENCY_DEP_FILE", "severity": "HIGH", "details": {"file_path": "/Users/david/Desktop/notebook_scanner/test_notebooks/requirements.txt", "results": {"VulnerabilityID": "CVE-2018-1000656", "PkgName": "flask", "InstalledVersion": "0.12.2", "FixedVersion": "0.12.3", "Layer": {}, "SeveritySource": "ghsa", "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2018-1000656", "DataSource": {"ID": "ghsa", "Name": "GitHub Security Advisory pip", "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"}, "Title": "python-flask: Denial of Service via crafted JSON file", "Description": "The Pallets Project flask version Before 0.12.3 contains a CWE-20: Improper Input Validation vulnerability in flask that can result in Large amount of memory usage possibly leading to denial of service. This attack appear to be exploitable via Attacker provides JSON data in incorrect encoding. This vulnerability appears to have been fixed in 0.12.3. NOTE: this may overlap CVE-2019-1010083.", "Severity": "HIGH", "CweIDs": ["CWE-20"], "CVSS": {"ghsa": {"V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H", "V3Score": 7.5}, "nvd": {"V2Vector": "AV:N/AC:L/Au:N/C:N/I:N/A:P", "V3Vector": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H", "V2Score": 5, "V3Score": 7.5}, "redhat": {"V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H", "V3Score": 7.5}}, "References": ["https://access.redhat.com/security/cve/CVE-2018-1000656", "https://github.com/advisories/GHSA-562c-5r94-xh97", "https://github.com/pallets/flask", "https://github.com/pallets/flask/commit/b178e89e4456e777b1a7ac6d7199052d0dfdbbbe", "https://github.com/pallets/flask/pull/2691", "https://github.com/pallets/flask/releases/tag/0.12.3", "https://lists.debian.org/debian-lts-announce/2019/08/msg00025.html", "https://nvd.nist.gov/vuln/detail/CVE-2018-1000656", "https://security.netapp.com/advisory/ntap-20190221-0001", "https://security.netapp.com/advisory/ntap-20190221-0001/", "https://ubuntu.com/security/notices/USN-4378-1", "https://usn.ubuntu.com/4378-1", "https://usn.ubuntu.com/4378-1/", "https://www.cve.org/CVERecord?id=CVE-2018-1000656"], "PublishedDate": "2018-08-20T19:31:45.34Z", "LastModifiedDate": "2020-06-09T22:15:10.943Z"}}}, {"code": "VULNERABLE_DEPENDENCY_DEP_FILE", "severity": "HIGH", "details": {"file_path": "/Users/david/Desktop/notebook_scanner/test_notebooks/requirements.txt", "results": {"VulnerabilityID": "CVE-2019-1010083", "PkgName": "flask", "InstalledVersion": "0.12.2", "FixedVersion": "1.0", "Layer": {}, "SeveritySource": "ghsa", "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2019-1010083", "DataSource": {"ID": "ghsa", "Name": "GitHub Security Advisory pip", "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"}, "Title": "python-flask: unexpected memory usage can lead to denial of service via crafted encoded JSON data", "Description": "The Pallets Project Flask before 1.0 is affected by: unexpected memory usage. The impact is: denial of service. The attack vector is: crafted encoded JSON data. The fixed version is: 1. NOTE: this may overlap CVE-2018-1000656.", "Severity": "HIGH", "CVSS": {"ghsa": {"V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H", "V3Score": 7.5}, "nvd": {"V2Vector": "AV:N/AC:L/Au:N/C:N/I:N/A:P", "V3Vector": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H", "V2Score": 5, "V3Score": 7.5}, "redhat": {"V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H", "V3Score": 7.5}}, "References": ["https://access.redhat.com/security/cve/CVE-2019-1010083", "https://github.com/pallets/flask", "https://nvd.nist.gov/vuln/detail/CVE-2019-1010083", "https://palletsprojects.com/blog/flask-1-0-released/", "https://snyk.io/vuln/SNYK-PYTHON-FLASK-451637", "https://www.cve.org/CVERecord?id=CVE-2019-1010083", "https://www.palletsprojects.com/blog/flask-1-0-released", "https://www.palletsprojects.com/blog/flask-1-0-released/"], "PublishedDate": "2019-07-17T14:15:11.57Z", "LastModifiedDate": "2020-08-24T17:37:01.14Z"}}}, {"code": "VULNERABLE_DEPENDENCY_DEP_FILE", "severity": "HIGH", "details": {"file_path": "/Users/david/Desktop/notebook_scanner/test_notebooks/requirements.txt", "results": {"VulnerabilityID": "CVE-2023-30861", "PkgName": "flask", "InstalledVersion": "0.12.2", "FixedVersion": "2.3.2, 2.2.5", "Layer": {}, "SeveritySource": "ghsa", "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2023-30861", "DataSource": {"ID": "ghsa", "Name": "GitHub Security Advisory pip", "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"}, "Title": "flask: Possible disclosure of permanent session cookie due to missing Vary: Cookie header", "Description": "Flask is a lightweight WSGI web application framework. When all of the following conditions are met, a response containing data intended for one client may be cached and subsequently sent by the proxy to other clients. If the proxy also caches `Set-Cookie` headers, it may send one client's `session` cookie to other clients. The severity depends on the application's use of the session and the proxy's behavior regarding cookies. The risk depends on all these conditions being met.\n\n1. The application must be hosted behind a caching proxy that does not strip cookies or ignore responses with cookies.\n2. The application sets `session.permanent = True`\n3. The application does not access or modify the session at any point during a request.\n4. `SESSION_REFRESH_EACH_REQUEST` enabled (the default).\n5. The application does not set a `Cache-Control` header to indicate that a page is private or should not be cached.\n\nThis happens because vulnerable versions of Flask only set the `Vary: Cookie` header when the session is accessed or modified, not when it is refreshed (re-sent to update the expiration) without being accessed or modified. This issue has been fixed in versions 2.3.2 and 2.2.5.", "Severity": "HIGH", "CweIDs": ["CWE-539"], "CVSS": {"ghsa": {"V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N", "V3Score": 7.5}, "nvd": {"V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N", "V3Score": 7.5}, "redhat": {"V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N", "V3Score": 7.5}}, "References": ["https://access.redhat.com/security/cve/CVE-2023-30861", "https://github.com/pallets/flask", "https://github.com/pallets/flask/commit/70f906c51ce49c485f1d355703e9cc3386b1cc2b", "https://github.com/pallets/flask/commit/8646edca6f47e2cd57464081b3911218d4734f8d (2.2.5)", "https://github.com/pallets/flask/commit/8705dd39c4fa563ea0fe0bf84c85da8fcc98b88d (2.3.2)", "https://github.com/pallets/flask/commit/afd63b16170b7c047f5758eb910c416511e9c965", "https://github.com/pallets/flask/releases/tag/2.2.5", "https://github.com/pallets/flask/releases/tag/2.3.2", "https://github.com/pallets/flask/security/advisories/GHSA-m2qf-hxjv-5gpq", "https://github.com/pypa/advisory-database/tree/main/vulns/flask/PYSEC-2023-62.yaml", "https://linux.oracle.com/cve/CVE-2023-30861.html", "https://linux.oracle.com/errata/ELSA-2023-12710.html", "https://lists.debian.org/debian-lts-announce/2023/08/msg00024.html", "https://nvd.nist.gov/vuln/detail/CVE-2023-30861", "https://security.netapp.com/advisory/ntap-20230818-0006", "https://security.netapp.com/advisory/ntap-20230818-0006/", "https://ubuntu.com/security/notices/USN-6111-1", "https://www.cve.org/CVERecord?id=CVE-2023-30861", "https://www.debian.org/security/2023/dsa-5442"], "PublishedDate": "2023-05-02T18:15:52.373Z", "LastModifiedDate": "2023-08-20T21:15:09.46Z"}}}, {"code": "VULNERABLE_DEPENDENCY_DEP_FILE", "severity": "CRITICAL", "details": {"file_path": "/Users/david/Desktop/notebook_scanner/test_notebooks/requirements.txt", "results": {"VulnerabilityID": "CVE-2019-6446", "PkgName": "numpy", "InstalledVersion": "1.16.0", "Layer": {}, "SeveritySource": "ghsa", "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2019-6446", "DataSource": {"ID": "ghsa", "Name": "GitHub Security Advisory pip", "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"}, "Title": "numpy: crafted serialized object passed in numpy.load() in pickle python module allows arbitrary code execution", "Description": "An issue was discovered in NumPy 1.16.0 and earlier. It uses the pickle Python module unsafely, which allows remote attackers to execute arbitrary code via a crafted serialized object, as demonstrated by a numpy.load call. NOTE: third parties dispute this issue because it is  a behavior that might have legitimate applications in (for example)  loading serialized Python object arrays from trusted and authenticated  sources", "Severity": "CRITICAL", "CweIDs": ["CWE-502"], "CVSS": {"ghsa": {"V3Vector": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H", "V3Score": 9.8}, "nvd": {"V2Vector": "AV:N/AC:L/Au:N/C:P/I:P/A:P", "V3Vector": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H", "V2Score": 7.5, "V3Score": 9.8}, "redhat": {"V3Vector": "CVSS:3.0/AV:N/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H", "V3Score": 8.8}}, "References": ["http://lists.opensuse.org/opensuse-security-announce/2019-09/msg00091.html", "http://lists.opensuse.org/opensuse-security-announce/2019-09/msg00092.html", "http://lists.opensuse.org/opensuse-security-announce/2019-10/msg00015.html", "http://www.securityfocus.com/bid/106670", "https://access.redhat.com/errata/RHSA-2019:3335", "https://access.redhat.com/errata/RHSA-2019:3704", "https://access.redhat.com/security/cve/CVE-2019-6446", "https://bugzilla.suse.com/show_bug.cgi?id=1122208", "https://errata.almalinux.org/8/ALSA-2019-3335.html", "https://github.com/numpy/numpy", "https://github.com/numpy/numpy/issues/12759", "https://github.com/numpy/numpy/pull/12889", "https://linux.oracle.com/cve/CVE-2019-6446.html", "https://linux.oracle.com/errata/ELSA-2019-3704.html", "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/7ZZAYIQNUUYXGMKHSPEEXS4TRYFOUYE4", "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/7ZZAYIQNUUYXGMKHSPEEXS4TRYFOUYE4/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/7ZZAYIQNUUYXGMKHSPEEXS4TRYFOUYE4", "https://nvd.nist.gov/vuln/detail/CVE-2019-6446", "https://web.archive.org/web/20210124234613/https://www.securityfocus.com/bid/106670", "https://www.cve.org/CVERecord?id=CVE-2019-6446"], "PublishedDate": "2019-01-16T05:29:01.37Z", "LastModifiedDate": "2024-08-04T21:15:28.97Z"}}}, {"code": "VULNERABLE_DEPENDENCY_DEP_FILE", "severity": "HIGH", "details": {"file_path": "/Users/david/Desktop/notebook_scanner/test_notebooks/requirements.txt", "results": {"VulnerabilityID": "CVE-2021-41495", "PkgName": "numpy", "InstalledVersion": "1.16.0", "FixedVersion": "1.19", "Layer": {}, "SeveritySource": "ghsa", "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2021-41495", "DataSource": {"ID": "ghsa", "Name": "GitHub Security Advisory pip", "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"}, "Title": "numpy: NULL pointer dereference in numpy.sort in in the PyArray_DescrNew() due to missing return-value validation", "Description": "Null Pointer Dereference vulnerability exists in numpy.sort in NumPy &lt and 1.19 in the PyArray_DescrNew function due to missing return-value validation, which allows attackers to conduct DoS attacks by repetitively creating sort arrays. NOTE: While correct that validation is missing, an error can only occur due to an exhaustion of memory. If the user can exhaust memory, they are already privileged. Further, it should be practically impossible to construct an attack which can target the memory exhaustion to occur at exactly this place", "Severity": "HIGH", "CweIDs": ["CWE-476"], "CVSS": {"ghsa": {"V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H", "V3Score": 7.5}, "nvd": {"V2Vector": "AV:N/AC:M/Au:S/C:N/I:N/A:P", "V3Vector": "CVSS:3.1/AV:N/AC:H/PR:L/UI:N/S:U/C:N/I:N/A:H", "V2Score": 3.5, "V3Score": 5.3}, "redhat": {"V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H", "V3Score": 7.5}}, "References": ["https://access.redhat.com/security/cve/CVE-2021-41495", "https://github.com/advisories/GHSA-5545-2q6w-2gh6", "https://github.com/numpy/numpy", "https://github.com/numpy/numpy/issues/19038", "https://github.com/numpy/numpy/pull/20960", "https://github.com/numpy/numpy/pull/20984 (backport)", "https://github.com/pypa/advisory-database/tree/main/vulns/numpy/PYSEC-2021-856.yaml", "https://nvd.nist.gov/vuln/detail/CVE-2021-41495", "https://ubuntu.com/security/notices/USN-5763-1", "https://www.cve.org/CVERecord?id=CVE-2021-41495", "https://www.oracle.com/security-alerts/cpujul2022.html"], "PublishedDate": "2021-12-17T20:15:08.477Z", "LastModifiedDate": "2024-08-04T04:15:39.51Z"}}}, {"code": "VULNERABLE_DEPENDENCY_DEP_FILE", "severity": "MEDIUM", "details": {"file_path": "/Users/david/Desktop/notebook_scanner/test_notebooks/requirements.txt", "results": {"VulnerabilityID": "CVE-2021-33430", "PkgName": "numpy", "InstalledVersion": "1.16.0", "FixedVersion": "1.21", "Layer": {}, "SeveritySource": "ghsa", "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2021-33430", "DataSource": {"ID": "ghsa", "Name": "GitHub Security Advisory pip", "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"}, "Title": "numpy: buffer overflow in the PyArray_NewFromDescr_int() in ctors.c", "Description": "A Buffer Overflow vulnerability exists in NumPy 1.9.x in the PyArray_NewFromDescr_int function of ctors.c when specifying arrays of large dimensions (over 32) from Python code, which could let a malicious user cause a Denial of Service. NOTE: The vendor does not agree this is a vulneraility; In (very limited) circumstances a user may be able provoke the buffer overflow, the user is most likely already privileged to at least provoke denial of service by exhausting memory. Triggering this further requires the use of uncommon API (complicated structured dtypes), which is very unlikely to be available to an unprivileged user", "Severity": "MEDIUM", "CweIDs": ["CWE-120"], "CVSS": {"ghsa": {"V3Vector": "CVSS:3.1/AV:N/AC:H/PR:L/UI:N/S:U/C:N/I:N/A:H", "V3Score": 5.3}, "nvd": {"V2Vector": "AV:N/AC:M/Au:S/C:N/I:N/A:P", "V3Vector": "CVSS:3.1/AV:N/AC:H/PR:L/UI:N/S:U/C:N/I:N/A:H", "V2Score": 3.5, "V3Score": 5.3}, "redhat": {"V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H", "V3Score": 7.5}}, "References": ["https://access.redhat.com/security/cve/CVE-2021-33430", "https://github.com/numpy/numpy", "https://github.com/numpy/numpy/commit/16f7824b4d935b6aee98298ca4123d57174a6f2e (v1.22.0.dev0)", "https://github.com/numpy/numpy/commit/ae317fd9ff3e79c0eac357d723bfc29cbd625f2e", "https://github.com/numpy/numpy/issues/18939", "https://github.com/numpy/numpy/pull/18989", "https://nvd.nist.gov/vuln/detail/CVE-2021-33430", "https://ubuntu.com/security/notices/USN-5763-1", "https://www.cve.org/CVERecord?id=CVE-2021-33430"], "PublishedDate": "2021-12-17T19:15:07.5Z", "LastModifiedDate": "2024-08-04T00:15:32.943Z"}}}, {"code": "VULNERABLE_DEPENDENCY_DEP_FILE", "severity": "MEDIUM", "details": {"file_path": "/Users/david/Desktop/notebook_scanner/test_notebooks/requirements.txt", "results": {"VulnerabilityID": "CVE-2021-34141", "PkgName": "numpy", "InstalledVersion": "1.16.0", "FixedVersion": "1.22", "Layer": {}, "SeveritySource": "ghsa", "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2021-34141", "DataSource": {"ID": "ghsa", "Name": "GitHub Security Advisory pip", "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"}, "Title": "numpy: incomplete string comparison in the numpy.core component", "Description": "An incomplete string comparison in the numpy.core component in NumPy before 1.22.0 allows attackers to trigger slightly incorrect copying by constructing specific string objects. NOTE: the vendor states that this reported code behavior is \"completely harmless.\"", "Severity": "MEDIUM", "CweIDs": ["CWE-697"], "CVSS": {"ghsa": {"V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:L", "V3Score": 5.3}, "nvd": {"V2Vector": "AV:N/AC:L/Au:N/C:N/I:N/A:P", "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:L", "V2Score": 5, "V3Score": 5.3}, "redhat": {"V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:L", "V3Score": 5.3}}, "References": ["https://access.redhat.com/security/cve/CVE-2021-34141", "https://github.com/advisories/GHSA-fpfv-jqm9-f5jm", "https://github.com/numpy/numpy", "https://github.com/numpy/numpy/commit/eeef9d4646103c3b1afd3085f1393f2b3f9575b2 (v1.23.0.dev0)", "https://github.com/numpy/numpy/issues/18993", "https://github.com/numpy/numpy/issues/18993#issuecomment-1010735102", "https://github.com/pypa/advisory-database/tree/main/vulns/numpy/PYSEC-2021-855.yaml", "https://nvd.nist.gov/vuln/detail/CVE-2021-34141", "https://ubuntu.com/security/notices/USN-5763-1", "https://www.cve.org/CVERecord?id=CVE-2021-34141", "https://www.oracle.com/security-alerts/cpujul2022.html"], "PublishedDate": "2021-12-17T19:15:07.543Z", "LastModifiedDate": "2023-02-24T15:35:45.593Z"}}}, {"code": "VULNERABLE_DEPENDENCY_DEP_FILE", "severity": "MEDIUM", "details": {"file_path": "/Users/david/Desktop/notebook_scanner/test_notebooks/requirements.txt", "results": {"VulnerabilityID": "CVE-2021-41496", "PkgName": "numpy", "InstalledVersion": "1.16.0", "FixedVersion": "1.19", "Layer": {}, "SeveritySource": "ghsa", "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2021-41496", "DataSource": {"ID": "ghsa", "Name": "GitHub Security Advisory pip", "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"}, "Title": "numpy: buffer overflow in the array_from_pyobj() in fortranobject.c", "Description": "Buffer overflow in the array_from_pyobj function of fortranobject.c in NumPy < 1.19, which allows attackers to conduct a Denial of Service attacks by carefully constructing an array with negative values. NOTE: The vendor does not agree this is a vulnerability; the negative dimensions can only be created by an already privileged user (or internally)", "Severity": "MEDIUM", "CweIDs": ["CWE-120"], "CVSS": {"ghsa": {"V3Vector": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H", "V3Score": 5.5}, "nvd": {"V2Vector": "AV:L/AC:L/Au:N/C:N/I:N/A:P", "V3Vector": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H", "V2Score": 2.1, "V3Score": 5.5}, "redhat": {"V3Vector": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H", "V3Score": 5.5}}, "References": ["https://access.redhat.com/security/cve/CVE-2021-41496", "https://github.com/numpy/numpy", "https://github.com/numpy/numpy/commit/271010f1037150e95017f803f4214b8861e528f2", "https://github.com/numpy/numpy/issues/19000", "https://github.com/numpy/numpy/pull/20630", "https://nvd.nist.gov/vuln/detail/CVE-2021-41496", "https://ubuntu.com/security/notices/USN-5763-1", "https://www.cve.org/CVERecord?id=CVE-2021-41496", "https://www.oracle.com/security-alerts/cpujul2022.html"], "PublishedDate": "2021-12-17T20:15:08.517Z", "LastModifiedDate": "2024-08-04T04:15:44.11Z"}}}, {"code": "VULNERABLE_DEPENDENCY_DEP_FILE", "severity": "HIGH", "details": {"file_path": "/Users/david/Desktop/notebook_scanner/test_notebooks/requirements.txt", "results": {"VulnerabilityID": "CVE-2018-18074", "PkgName": "requests", "InstalledVersion": "2.19.1", "FixedVersion": "2.20.0", "Layer": {}, "SeveritySource": "ghsa", "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2018-18074", "DataSource": {"ID": "ghsa", "Name": "GitHub Security Advisory pip", "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"}, "Title": "python-requests: Redirect from HTTPS to HTTP does not remove Authorization header", "Description": "The Requests package before 2.20.0 for Python sends an HTTP Authorization header to an http URI upon receiving a same-hostname https-to-http redirect, which makes it easier for remote attackers to discover credentials by sniffing the network.", "Severity": "HIGH", "CweIDs": ["CWE-522"], "CVSS": {"ghsa": {"V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N", "V3Score": 7.5}, "nvd": {"V2Vector": "AV:N/AC:L/Au:N/C:P/I:N/A:N", "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N", "V2Score": 5, "V3Score": 7.5}, "redhat": {"V3Vector": "CVSS:3.0/AV:A/AC:H/PR:N/UI:R/S:U/C:L/I:N/A:N", "V3Score": 2.6}}, "References": ["http://docs.python-requests.org/en/master/community/updates/#release-and-version-history", "http://lists.opensuse.org/opensuse-security-announce/2019-07/msg00024.html", "https://access.redhat.com/errata/RHSA-2019:2035", "https://access.redhat.com/security/cve/CVE-2018-18074", "https://bugs.debian.org/910766", "https://errata.almalinux.org/8/ALSA-2020-1605.html", "https://github.com/advisories/GHSA-x84v-xcm2-53pg", "https://github.com/requests/requests", "https://github.com/requests/requests/commit/c45d7c49ea75133e52ab22a8e9e13173938e36ff", "https://github.com/requests/requests/issues/4716", "https://github.com/requests/requests/pull/4718", "https://linux.oracle.com/cve/CVE-2018-18074.html", "https://linux.oracle.com/errata/ELSA-2020-2081.html", "https://nvd.nist.gov/vuln/detail/CVE-2018-18074", "https://ubuntu.com/security/notices/USN-3790-1", "https://ubuntu.com/security/notices/USN-3790-2", "https://usn.ubuntu.com/3790-1", "https://usn.ubuntu.com/3790-1/", "https://usn.ubuntu.com/3790-2", "https://usn.ubuntu.com/3790-2/", "https://www.cve.org/CVERecord?id=CVE-2018-18074", "https://www.oracle.com/security-alerts/cpujul2022.html"], "PublishedDate": "2018-10-09T17:29:01.897Z", "LastModifiedDate": "2022-07-25T18:15:14.467Z"}}}, {"code": "VULNERABLE_DEPENDENCY_DEP_FILE", "severity": "MEDIUM", "details": {"file_path": "/Users/david/Desktop/notebook_scanner/test_notebooks/requirements.txt", "results": {"VulnerabilityID": "CVE-2023-32681", "PkgName": "requests", "InstalledVersion": "2.19.1", "FixedVersion": "2.31.0", "Layer": {}, "SeveritySource": "ghsa", "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2023-32681", "DataSource": {"ID": "ghsa", "Name": "GitHub Security Advisory pip", "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"}, "Title": "python-requests: Unintended leak of Proxy-Authorization header", "Description": "Requests is a HTTP library. Since Requests 2.3.0, Requests has been leaking Proxy-Authorization headers to destination servers when redirected to an HTTPS endpoint. This is a product of how we use `rebuild_proxies` to reattach the `Proxy-Authorization` header to requests. For HTTP connections sent through the tunnel, the proxy will identify the header in the request itself and remove it prior to forwarding to the destination server. However when sent over HTTPS, the `Proxy-Authorization` header must be sent in the CONNECT request as the proxy has no visibility into the tunneled request. This results in Requests forwarding proxy credentials to the destination server unintentionally, allowing a malicious actor to potentially exfiltrate sensitive information. This issue has been patched in version 2.31.0.\n\n", "Severity": "MEDIUM", "CweIDs": ["CWE-200"], "CVSS": {"ghsa": {"V3Vector": "CVSS:3.1/AV:N/AC:H/PR:N/UI:R/S:C/C:H/I:N/A:N", "V3Score": 6.1}, "nvd": {"V3Vector": "CVSS:3.1/AV:N/AC:H/PR:N/UI:R/S:C/C:H/I:N/A:N", "V3Score": 6.1}, "redhat": {"V3Vector": "CVSS:3.1/AV:N/AC:H/PR:N/UI:R/S:C/C:H/I:N/A:N", "V3Score": 6.1}}, "References": ["https://access.redhat.com/errata/RHSA-2023:4350", "https://access.redhat.com/security/cve/CVE-2023-32681", "https://bugzilla.redhat.com/2209469", "https://bugzilla.redhat.com/show_bug.cgi?id=2209469", "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2023-32681", "https://errata.almalinux.org/9/ALSA-2023-4350.html", "https://errata.rockylinux.org/RLSA-2023:4520", "https://github.com/psf/requests", "https://github.com/psf/requests/commit/74ea7cf7a6a27a4eeb2ae24e162bcc942a6706d5", "https://github.com/psf/requests/releases/tag/v2.31.0", "https://github.com/psf/requests/security/advisories/GHSA-j8r2-6x86-q33q", "https://github.com/pypa/advisory-database/tree/main/vulns/requests/PYSEC-2023-74.yaml", "https://linux.oracle.com/cve/CVE-2023-32681.html", "https://linux.oracle.com/errata/ELSA-2023-7050.html", "https://lists.debian.org/debian-lts-announce/2023/06/msg00018.html", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/AW7HNFGYP44RT3DUDQXG2QT3OEV2PJ7Y", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/AW7HNFGYP44RT3DUDQXG2QT3OEV2PJ7Y/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/KOYASTZDGQG2BWLSNBPL3TQRL2G7QYNZ", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/KOYASTZDGQG2BWLSNBPL3TQRL2G7QYNZ/", "https://nvd.nist.gov/vuln/detail/CVE-2023-32681", "https://security.gentoo.org/glsa/202309-08", "https://ubuntu.com/security/notices/USN-6155-1", "https://ubuntu.com/security/notices/USN-6155-2", "https://www.cve.org/CVERecord?id=CVE-2023-32681"], "PublishedDate": "2023-05-26T18:15:14.147Z", "LastModifiedDate": "2023-09-17T09:15:12.327Z"}}}, {"code": "VULNERABLE_DEPENDENCY_DEP_FILE", "severity": "MEDIUM", "details": {"file_path": "/Users/david/Desktop/notebook_scanner/test_notebooks/requirements.txt", "results": {"VulnerabilityID": "CVE-2024-35195", "PkgName": "requests", "InstalledVersion": "2.19.1", "FixedVersion": "2.32.0", "Layer": {}, "SeveritySource": "ghsa", "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2024-35195", "DataSource": {"ID": "ghsa", "Name": "GitHub Security Advisory pip", "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"}, "Title": "requests: subsequent requests to the same host ignore cert verification", "Description": "Requests is a HTTP library. Prior to 2.32.0, when making requests through a Requests `Session`, if the first request is made with `verify=False` to disable cert verification, all subsequent requests to the same host will continue to ignore cert verification regardless of changes to the value of `verify`. This behavior will continue for the lifecycle of the connection in the connection pool. This vulnerability is fixed in 2.32.0.", "Severity": "MEDIUM", "CweIDs": ["CWE-670"], "CVSS": {"ghsa": {"V3Vector": "CVSS:3.1/AV:L/AC:H/PR:H/UI:R/S:U/C:H/I:H/A:N", "V3Score": 5.6}, "redhat": {"V3Vector": "CVSS:3.1/AV:L/AC:H/PR:H/UI:R/S:U/C:H/I:H/A:N", "V3Score": 5.6}}, "References": ["https://access.redhat.com/security/cve/CVE-2024-35195", "https://github.com/psf/requests", "https://github.com/psf/requests/commit/a58d7f2ffb4d00b46dca2d70a3932a0b37e22fac", "https://github.com/psf/requests/pull/6655", "https://github.com/psf/requests/security/advisories/GHSA-9wx4-h78v-vm56", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/IYLSNK5TL46Q6XPRVMHVWS63MVJQOK4Q", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/IYLSNK5TL46Q6XPRVMHVWS63MVJQOK4Q/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/N7WP6EYDSUOCOJYHDK5NX43PYZ4SNHGZ", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/N7WP6EYDSUOCOJYHDK5NX43PYZ4SNHGZ/", "https://nvd.nist.gov/vuln/detail/CVE-2024-35195", "https://www.cve.org/CVERecord?id=CVE-2024-35195"], "PublishedDate": "2024-05-20T21:15:09.99Z", "LastModifiedDate": "2024-06-10T17:16:29.563Z"}}}, {"code": "VULNERABLE_DEPENDENCY_DEP_FILE", "severity": "CRITICAL", "details": {"file_path": "/Users/david/Desktop/notebook_scanner/test_notebooks/requirements.txt", "results": {"VulnerabilityID": "CVE-2020-13092", "PkgName": "scikit-learn", "InstalledVersion": "0.19.0", "Layer": {}, "SeveritySource": "ghsa", "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2020-13092", "DataSource": {"ID": "ghsa", "Name": "GitHub Security Advisory pip", "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"}, "Title": "scikit-learn (aka sklearn) through 0.23.0 can unserialize and execute  ...", "Description": "scikit-learn (aka sklearn) through 0.23.0 can unserialize and execute commands from an untrusted file that is passed to the joblib.load() function, if __reduce__ makes an os.system call. NOTE: third parties dispute this issue because the joblib.load() function is documented as unsafe and it is the user's responsibility to use the function in a secure manner", "Severity": "CRITICAL", "CweIDs": ["CWE-502"], "CVSS": {"ghsa": {"V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H", "V3Score": 9.8}, "nvd": {"V2Vector": "AV:N/AC:L/Au:N/C:P/I:P/A:P", "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H", "V2Score": 7.5, "V3Score": 9.8}}, "References": ["https://github.com/0FuzzingQ/vuln/blob/master/sklearn%20unserialize.md", "https://github.com/scikit-learn/scikit-learn", "https://nvd.nist.gov/vuln/detail/CVE-2020-13092", "https://scikit-learn.org/stable/modules/model_persistence.html#security-maintainability-limitations"], "PublishedDate": "2020-05-15T19:15:12.277Z", "LastModifiedDate": "2024-08-04T12:15:57.637Z"}}}, {"code": "VULNERABLE_DEPENDENCY_DEP_FILE", "severity": "MEDIUM", "details": {"file_path": "/Users/david/Desktop/notebook_scanner/test_notebooks/requirements.txt", "results": {"VulnerabilityID": "CVE-2024-5206", "PkgName": "scikit-learn", "InstalledVersion": "0.19.0", "FixedVersion": "1.5.0", "Layer": {}, "SeveritySource": "ghsa", "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2024-5206", "DataSource": {"ID": "ghsa", "Name": "GitHub Security Advisory pip", "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"}, "Title": "scikit-learn: Possible sensitive data leak", "Description": "A sensitive data leakage vulnerability was identified in scikit-learn's TfidfVectorizer, specifically in versions up to and including 1.4.1.post1, which was fixed in version 1.5.0. The vulnerability arises from the unexpected storage of all tokens present in the training data within the `stop_words_` attribute, rather than only storing the subset of tokens required for the TF-IDF technique to function. This behavior leads to the potential leakage of sensitive information, as the `stop_words_` attribute could contain tokens that were meant to be discarded and not stored, such as passwords or keys. The impact of this vulnerability varies based on the nature of the data being processed by the vectorizer.", "Severity": "MEDIUM", "CweIDs": ["CWE-921"], "CVSS": {"ghsa": {"V3Vector": "CVSS:3.0/AV:N/AC:H/PR:L/UI:N/S:U/C:H/I:N/A:N", "V3Score": 5.3}, "redhat": {"V3Vector": "CVSS:3.0/AV:N/AC:H/PR:L/UI:N/S:U/C:H/I:N/A:N", "V3Score": 5.3}}, "References": ["https://access.redhat.com/security/cve/CVE-2024-5206", "https://github.com/scikit-learn/scikit-learn", "https://github.com/scikit-learn/scikit-learn/commit/70ca21f106b603b611da73012c9ade7cd8e438b8", "https://huntr.com/bounties/14bc0917-a85b-4106-a170-d09d5191517c", "https://nvd.nist.gov/vuln/detail/CVE-2024-5206", "https://www.cve.org/CVERecord?id=CVE-2024-5206"], "PublishedDate": "2024-06-06T19:16:06.363Z", "LastModifiedDate": "2024-06-17T19:15:59.19Z"}}}], "plugins": [{"name": "PII Plugin", "settings": {"enabled": true, "confidence_threshold": 0.8, "entities": {"US_PASSPORT": true, "AU_MEDICARE": true, "AU_TFN": true, "AU_ACN": true, "AU_ABN": true, "UK_NHS": true, "US_SSN": true, "US_ITIN": true, "US_DRIVER_LICENSE": true, "US_BANK_NUMBER": true, "MEDICAL_LICENSE": true, "LOCATION": true, "PHONE_NUMBER": true, "NRP": true, "IP_ADDRESS": true, "EMAIL_ADDRESS": true, "IBAN_CODE": true, "CRYPTO": true, "CREDIT_CARD": true, "PERSON": true}}}, {"name": "Secrets Plugin", "settings": {"enabled": true, "secrets_plugins": [{"name": "SoftlayerDetector"}, {"name": "StripeDetector"}, {"name": "SendGridDetector"}, {"name": "NpmDetector"}, {"name": "KeywordDetector", "keyword_exclude": ""}, {"name": "IbmCosHmacDetector"}, {"name": "DiscordBotTokenDetector"}, {"name": "BasicAuthDetector"}, {"name": "AzureStorageKeyDetector"}, {"name": "ArtifactoryDetector"}, {"name": "AWSKeyDetector"}, {"name": "CloudantDetector"}, {"name": "GitHubTokenDetector"}, {"name": "IbmCloudIamDetector"}, {"name": "JwtTokenDetector"}, {"name": "MailchimpDetector"}, {"name": "PrivateKeyDetector"}, {"name": "SlackDetector"}, {"name": "SquareOAuthDetector"}, {"name": "TwilioKeyDetector"}, {"name": "Base64HighEntropyString", "limit": 4.5}, {"name": "HexHighEntropyString", "limit": 3.0}]}}, {"name": "License Plugin for Dependency Files", "settings": {"enabled": true, "accepted_licenses": ["Apache License 2.0", "Apache Software License", "Apache 2.0", "Apache-2.0", "BSD", "BSD License", "BSD 3-Clause", "BSD-3-Clause", "GNU Library or Lesser General Public License (LGPL)", "Microsoft Public License", "MIT", "MIT License", "Python Software Foundation License", "ISC License (ISCL)", "MIT-0"]}}, {"name": "CVE Plugin for Dependency Files", "settings": {"enabled": true}}], "notebooks": ["/Users/david/Desktop/notebook_scanner/test_notebooks/classification_notebook.ipynb", "/Users/david/Desktop/notebook_scanner/test_notebooks/tpu_training-tf.ipynb", "/Users/david/Desktop/notebook_scanner/test_notebooks/text_classification_quantization_ort.ipynb"], "notebook_issues": [{"path": "/Users/david/Desktop/notebook_scanner/test_notebooks/classification_notebook.ipynb", "issues": [{"code": "PII_FOUND", "severity": "HIGH", "cell": {"cell_index": 4, "cell_type": "SOURCE", "scrubbed_content": "# PII Data\nemail = \"[PII]\"\nphone = \"123-456-7890\""}, "location": "INPUT", "details": {"description": "A total of 1 PII found in cell number 4", "summary_field": {"EMAIL_ADDRESS": 1}}, "issues": [{"code": "PII_FOUND", "severity": "HIGH", "cell": {"cell_index": 4, "cell_type": "SOURCE", "scrubbed_content": "# PII Data\nemail = \"[PII]\"\nphone = \"123-456-7890\""}, "line_index": 1, "location": "INPUT", "character_start_index": 9, "character_end_index": 29, "details": null}]}, {"code": "SECRETS", "severity": "CRITICAL", "cell": {"cell_index": 5, "cell_type": "SOURCE", "scrubbed_content": "# API Keys and secrets\nfb_app_secret = \"3e..2b\"\ndb_credentials = \"username:password@localhost:5432/mydatabase\""}, "line_index": 1, "location": "INPUT", "character_start_index": 17, "character_end_index": 49, "details": {"description": "Secret Keyword", "summary_field": null}}, {"code": "SECRETS", "severity": "CRITICAL", "cell": {"cell_index": 5, "cell_type": "SOURCE", "scrubbed_content": "# API Keys and secrets\nfb_app_secret = \"3e..2b\"\ndb_credentials = \"username:password@localhost:5432/mydatabase\""}, "line_index": 1, "location": "INPUT", "character_start_index": 17, "character_end_index": 49, "details": {"description": "Hex High Entropy String", "summary_field": null}}]}, {"path": "/Users/david/Desktop/notebook_scanner/test_notebooks/tpu_training-tf.ipynb", "issues": []}, {"path": "/Users/david/Desktop/notebook_scanner/test_notebooks/text_classification_quantization_ort.ipynb", "issues": [{"code": "PII_FOUND", "severity": "HIGH", "cell": {"cell_index": 29, "cell_type": "SOURCE", "scrubbed_content": "from optimum.onnxruntime.configuration import QuantizationConfig, AutoCalibrationConfig\nfrom optimum.onnxruntime.quantization import QuantFormat, QuantizationMode, QuantType\n\nper_channel = False\nnum_calibration_samples = 40\noperators_to_quantize = [\"[PII]\", \"Add\", \"Gather\"] \napply_static_quantization = quantization_approach == \"static\"\n\nqconfig = QuantizationConfig(\n    is_static=apply_static_quantization,\n    format=QuantFormat.QDQ if apply_static_quantization else QuantFormat.QOperator,\n    mode=QuantizationMode.QLinearOps if apply_static_quantization else QuantizationMode.IntegerOps,\n    activations_dtype=QuantType.QInt8 if apply_static_quantization else QuantType.QUInt8,\n    weights_dtype=QuantType.QInt8,\n    per_channel=per_channel,\n    operators_to_quantize=operators_to_quantize,\n)"}, "location": "INPUT", "details": {"description": "A total of 1 PII found in cell number 29", "summary_field": {"PERSON": 1}}, "issues": [{"code": "PII_FOUND", "severity": "HIGH", "cell": {"cell_index": 29, "cell_type": "SOURCE", "scrubbed_content": "from optimum.onnxruntime.configuration import QuantizationConfig, AutoCalibrationConfig\nfrom optimum.onnxruntime.quantization import QuantFormat, QuantizationMode, QuantType\n\nper_channel = False\nnum_calibration_samples = 40\noperators_to_quantize = [\"[PII]\", \"Add\", \"Gather\"] \napply_static_quantization = quantization_approach == \"static\"\n\nqconfig = QuantizationConfig(\n    is_static=apply_static_quantization,\n    format=QuantFormat.QDQ if apply_static_quantization else QuantFormat.QOperator,\n    mode=QuantizationMode.QLinearOps if apply_static_quantization else QuantizationMode.IntegerOps,\n    activations_dtype=QuantType.QInt8 if apply_static_quantization else QuantType.QUInt8,\n    weights_dtype=QuantType.QInt8,\n    per_channel=per_channel,\n    operators_to_quantize=operators_to_quantize,\n)"}, "line_index": 5, "location": "INPUT", "character_start_index": 26, "character_end_index": 32, "details": null}]}]}]}
